#!/bin/bash
set -e

COMPONENTDIR=$(pwd)
ROS_DISTRO="kinetic"

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# Install packages
apt-get install -q -y \
    dirmngr \
    gnupg2 \
    lsb-release

sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
apt-get update

# install bootstrap tools
apt-get install -y \
  python-rosdep \
  python-rosinstall \
  python-vcstools \
  python-rosinstall-generator \
  ros-kinetic-opencv3 \
  ros-kinetic-cv-bridge \
  ros-kinetic-desktop  

# setup env
source /opt/ros/kinetic/setup.bash

catkin_make -DCMAKE_INSTALL_PREFIX=/opt/ros/kinetic install

# install the stuff
source install/setup.bash